service: dynamodb-resources

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  stackName: ${self:service}-${self:provider.stage}-stack

custom:
  defaultStage: dev
  regionAbbr:
    ap-northeast-2: an2

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-test-table
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createAt
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: createAt
            AttributeType: S
        #ProvisionedThroughput:
        #  ReadCapacityUnits: 5
        #  WriteCapacityUnits: 5
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES